import { createAsyncThunk } from '@reduxjs/toolkit';

export const fetchCustomerList = createAsyncThunk('customerList/fetchCustomerList', async () => {
  return {
    status: true,
    message: 'Success',
    data: [
      {
        id: 1,
        date: '20/07/2023',
        department: 'Tiểu phẫu',
        time: '8:20',
        name: 'Nguyễn Trà My',
        customerId: 1,
        service: '',
        account: 'KN123',
        status: 'Đã thanh toán',
        kip: '',
        bspt: '',
        ekip: '',
      },
      {
        id: 2,
        date: '20/07/2023',
        department: 'Tiểu phẫu',
        time: '8:20',
        name: 'Nguyễn Trà My',
        customerId: 2,
        service: '',
        account: 'KN123',
        status: 'Đã thanh toán',
        kip: '',
        bspt: '',
        ekip: '',
      },
      {
        id: 3,
        date: '20/07/2023',
        department: 'Tiểu phẫu',
        time: '8:20',
        name: 'Nguyễn Trà My',
        customerId: 3,
        service: '',
        account: 'KN123',
        status: 'Đã thanh toán',
        kip: '',
        bspt: '',
        ekip: '',
      },
      {
        id: 4,
        date: '20/07/2023',
        department: 'Tiểu phẫu',
        time: '8:20',
        name: 'Nguyễn Trà My',
        customerId: 4,
        service: '',
        account: 'KN123',
        status: 'Đã thanh toán',
        kip: '',
        bspt: '',
        ekip: '',
      },
      {
        id: 5,
        date: '20/07/2023',
        department: 'Tiểu phẫu',
        time: '8:20',
        name: 'Nguyễn Trà My',
        customerId: 5,
        service: '',
        account: 'KN123',
        status: 'Đã thanh toán',
        kip: '',
        bspt: '',
        ekip: '',
      },
    ],
  };
});
